// <auto-generated />
using System;
using Calificaciones.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calificaciones.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    partial class EscuelaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calificaciones.Models.SalonA", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<double?>("CalifFinal")
                        .HasColumnType("float");

                    b.Property<string>("NombreEstudiante")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("SemestreDos")
                        .HasColumnType("float");

                    b.Property<double?>("SemestreTres")
                        .HasColumnType("float");

                    b.Property<double?>("SemestreUno")
                        .HasColumnType("float");

                    b.HasKey("IdEstudiante")
                        .HasName("PK__SalonA__B5007C24815197A0");

                    b.ToTable("SalonA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
